### ISSUE TITLE
可以支持标签类型的span

### ISSUE THREAD

**Issue by goodluckier** [liangjingkanji/spannable#10]
大佬，能否支持下带边框或是背景色的标签，可以设置文字、边框、背景颜色，文字内边距，边框、背景可以设置圆角，就是都可以配置的span。常见的如下图
![1](https://user-images.githubusercontent.com/3511727/186302819-f433dcba-a84e-43b1-8d9b-8581955e3d48.png)
![2](https://user-images.githubusercontent.com/3511727/186302845-5804df33-f237-4c7b-b728-b847f597f495.png)
![3](https://user-images.githubusercontent.com/3511727/186302910-eb88583d-066b-40db-8ffc-83a4ad2b72cb.jpg)

**Comment by liangjingkanji** [comment]
1. 有考虑过, 但应当不会支持边框(这个由图片处理)
2. 目前也支持图片显示文字, 但是不支持根据文字缩放
3. 目前有优先级更高的项目, 所以暂时没空

欢迎贡献代码

**Comment by liangjingkanji** [comment]
本需求已经被标记为`enhancement`, 无需关闭

**Comment by liangjingkanji** [comment]
请升级最新版本, 支持shape/.9图可以实现你的需求
