### ISSUE TITLE
Demo安装失败,Android12

### ISSUE THREAD

**Issue by Iridescentangle** [liangjingkanji/spannable#11]
adb: failed to install /Users/$User/Downloads/spannale-sample.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed collecting certificates for /data/app/vmdl711509178.tmp/base.apk: Failed to collect certificates from /data/app/vmdl711509178.tmp/base.apk: Attempt to get length of null array]

**Comment by liangjingkanji** [comment]
请提供设备机型, 因为我无法复现问题, 请重新下载安装尝试

**Comment by Iridescentangle** [comment]
坚果Pro2，Android11
一加7T, Android12
均无法安装🤦🏻‍♀️

**Comment by liangjingkanji** [comment]
已修复请重试

**Comment by Iridescentangle** [comment]
赞，东哥速度👍🏻

**Comment by zs1973** [comment]
> 请提供设备机型, 因为我无法复现问题, 请重新下载安装尝试

真是高产似母猪啊 哈哈哈哈哈  几个框架并行维护  牛

**Comment by liangjingkanji** [comment]
> > 请提供设备机型, 因为我无法复现问题, 请重新下载安装尝试
> 
> 真是高产似母猪啊 哈哈哈哈哈 几个框架并行维护 牛

一起用一起维护而已, 也欢迎你star和pr
