### ISSUE TITLE
能否实现2行文本自动添加省略号后面添加图片的功能吧

### ISSUE THREAD

**Issue by Mrliandroid** [liangjingkanji/spannable#15]
https://blog.csdn.net/Eqiqi/article/details/125074007 类似这个功能 ，目前他这个有问题。我一行2行文本比较少，能正常，但是文本多了就不行了

**Comment by liangjingkanji** [comment]
目前就能实现, 这只是简单的字符串和图标拼接

**Comment by 598588152** [comment]
怎么拼接的，看下案例了
