### ISSUE TITLE
国际化问题

### ISSUE THREAD

**Issue by peter100u** [liangjingkanji/spannable#29]
设置 下面的key
<string name="coins_shouyi_liwushuom">(%sx%s)استلم</string>
国际化阿语的时候有问题 

val url = "https://avatars.githubusercontent.com/u/21078112?v=4"
        binding.tv1.text = getString(R.string.coins_shouyi_liwushuom).format(url,1).replaceSpan(url) {
            GlideImageSpan(binding.tv1, url).setDrawableSize(20.dp)
        }

设置            android:textDirection="ltr" 就没问题了，但是理论上应该不需要设置

**Comment by liangjingkanji** [comment]
有问题是什么问题？

**Comment by peter100u** [comment]
期望的结果在阿语的情况下，应该是
(图片x数量)استلم
现在的情况却是
图片(x数量)استلم， 你可以把上次的测试代码运行看下

**Comment by liangjingkanji** [comment]
我看不懂你的问题描述, 你提供的代码也不能直接运行

> 同时我没太多空闲时间为每个人的问题去运行代码看效果, 更何况你提供的也不是能够直接运行的代码

**Comment by liangjingkanji** [comment]
运行结果正常

<img width="127" alt="image" src="https://user-images.githubusercontent.com/21078112/224545914-0d28c669-d4e3-4f98-aa16-c59604cc64db.png">

**Comment by liangjingkanji** [comment]
我没有太多空闲为每个人运行代码, 请下次直接fork仓库复现问题, 除非你并不希望框架积极保持更新和问题回复

**Comment by liangjingkanji** [comment]
没有及时回复本问题将暂时关闭
