### ISSUE TITLE
CenterImageSpan内存泄露

### ISSUE THREAD

**Issue by xhh1993** [liangjingkanji/spannable#30]
偶现的CenterImageSpan内存泄露，
![1](https://github.com/liangjingkanji/spannable/assets/17424639/0cce5ec2-a3f1-4aa5-885f-dba8853f6b1b)
![2](https://github.com/liangjingkanji/spannable/assets/17424639/0f3388a0-5724-4a49-967e-e0639e348216)
![3](https://github.com/liangjingkanji/spannable/assets/17424639/12a0a613-47a2-4e3e-99d9-c7d6fa19cbfc)
![4](https://github.com/liangjingkanji/spannable/assets/17424639/216c39dd-6f02-4296-94ae-9c85fec701df)

**Comment by liangjingkanji** [comment]
我认为和本框架无关, CenterImageSpan只是继承ImageSpan, 并没有对mContext进行任何操作, 请排查下自己的代码

我猜测是你自己没有及时释放ImageSpan, 导致Act销毁ImageSpan依然被其他对象持有(而ImageSpan持有Act)

1. 传入全局Context
2. 及时释放

这问题我无法复现, 如果你能在demo中复现请fork仓库

**Comment by liangjingkanji** [comment]
解决了吗?

**Comment by xhh1993** [comment]
嗯，大概率是其他地方内存泄露引起的了。也不容易复现。修复了几个其他的内存泄露后目前为止没出现这个问题了

**Comment by liangjingkanji** [comment]
那我将关闭此问题, 后续还有问题继续反馈吧

觉得工具好用欢迎参与其中, star和推荐可以增加本仓库维护频率
