### ISSUE TITLE
在RecyclerView item里面的RecyclerView 里的item里面的textView设置HighlightSpan之后的点击事件无效

### ISSUE THREAD

**Issue by super963883929** [liangjingkanji/spannable#34]
简单来说就是一个RecyclerView里面的item嵌套一个RecyclerView ,再从嵌套里面的RecyclerView 的item放置TextView,然后再在这个Textview里面设置HighlightSpan的点击事件无法响应.
实际上嵌套的RecyclerView的item点击事件和item里面的TextView的点击事件都是可以响应的,但就是不能响应Textview设置了HighlightSpan的点击事件
![E52(2K81TXTLXLBNCZ)RQLV](https://github.com/liangjingkanji/spannable/assets/73236105/302a1d87-438e-4b09-8177-8312e95468b8)

**Comment by liangjingkanji** [comment]
应该是rv列表复用导致多个item设置了同一个span导致

**Comment by liangjingkanji** [comment]
如果不能响应你就自定义span吧, 反正HightSpan只是一个小小的简化类, 核心代码才两行

**Comment by super963883929** [comment]
好的
