### ISSUE TITLE
请教，删除的时候，如何还原之前的颜色？

### ISSUE THREAD

**Issue by chenkexu** [liangjingkanji/spannable#36]
比如，当我输入@某人的时候，显示了高亮，当我逐个输出文字，当只剩下@的时候，还原成之前的普通文本颜色

**Comment by chenkexu** [comment]
比如我设置正则‘@刘强东’精确匹配的时候，‘@刘强东’四个字符高亮，但是当我删除‘东’这个字符的时候，我希望文字恢复成普通的文本，而不是高亮，应该怎么解决？

**Comment by liangjingkanji** [comment]
你匹配什么高亮取决于你写的正则, 如果正则要求`@刘强东`, 那`@刘强`就不会高亮

一般这类功能实现监听的是整个输入框的文本, 哪分什么之前当前的, 只在乎现在的文本内容是否满足正则

**Comment by chenkexu** [comment]
我的正则表达式就是‘@刘强东’ 当我输入 ‘@刘强东’的时候，确实高亮了，但是当我删除最后一个字符‘东’的时候，此时只剩下‘@刘强’了，没有匹配到正则，在代码中直接return了，并没有返回之前的颜色。 @liangjingkanji

**Comment by liangjingkanji** [comment]
监听写错了吧, 删除的时候没有触发重新渲染TextView吧

自己debug下

**Comment by chenkexu** [comment]
忘记加了一行代码
