### ISSUE TITLE
在FrameLayout的弹窗中，点击事件没反应

### ISSUE THREAD

**Issue by yuandoudou928** [liangjingkanji/spannable#4]
我在第三方Popup框架“XPopup”中使用时，字体颜色改变了，点击事件没有反应，请问该怎么修改呢？

**Comment by liangjingkanji** [comment]
点击事件用ClickSpan或者HighlightSpan

你使用的Span都没说是什么示例代码也没有, 这怎么解决

**Comment by liangjingkanji** [comment]
没有回复我将关闭问题, 你还有疑问可以Reopen
