### ISSUE TITLE
java 调用有示例吗？

### ISSUE THREAD

**Issue by csh159** [liangjingkanji/spannable#7]

**Comment by liangjingkanji** [comment]
没有精力维护一套过时的语法示例，我只能说这个支持java, 会kt的人自然也会java调用

**Comment by csh159** [comment]
CharSequence temp = SpanUtilsKt.replaceSpan(txt, "隐私权政策", false, matchResult -> new ColorSpan("#479fd1"));
这样子吗？然后咋添加点击事件呐！

**Comment by liangjingkanji** [comment]
点击事件有`ClickSpan`或者`HighlightSpan `

另外这是简化处理官方的Spannable框架, 你可以搜索如何使用Spannable, 和本框架无关的问题不要讨论, 否则影响我处理bug
